---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/javascript"
    schedule:
      interval: "daily"
      time: "11:20"  # UTC
    commit-message:
      prefix: chore
      include: scope
  - package-ecosystem: bundler
    directory: "/ruby"
    schedule:
      interval: "weekly"
